Object Oriented Approach
Floor-Gang/modmail pull request #22
Opened 2021-01-27 19:35 UTC by dylhack

Rather than having controllers do everything in a functional sense, each entity will manage itself making this project heavily OOP. This will allow the code to be a lot cleaner.

2021-01-27 20:59 UTC, DankDumpster requested changes
And fix the mute :smile:

2021-01-27 20:59 UTC, DankDumpster commented on src/commands/categories/addcat.ts
> +      return null;
Unnecessary return

2021-01-27 20:59 UTC, DankDumpster commented on src/database/tables/threads.ts
> +  public async getByUser(userID: string): Promise<Thread | null> {
Comments?

2021-01-27 21:14 UTC, dylhack commented on src/database/tables/threads.ts
> +  public async getByUser(userID: string): Promise<Thread | null> {
It's a getter

2021-01-27 21:15 UTC, dylhack commented on src/commands/categories/addcat.ts
> +      return null;
Please read the function header

2021-01-27 21:17 UTC, dylhack commented on src/commands/categories/addcat.ts
> +      return null;
Resolved in d53ec67d2ccefee67690f96695a42eee1ed82287

2021-01-28 05:12 UTC, DankDumpster approved these changes
Lgtm

2021-01-28 05:14 UTC, merged